version: '3'
services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile.bot
    container_name: bot
    restart: always

  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    container_name: web
    restart: always
    ports:
      - "80:80"